
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaswant
 */
public class StudentReport extends javax.swing.JFrame {

    /**
     * Creates new form StudentReport
     */
    public StudentReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CmbBoxYear = new javax.swing.JComboBox();
        CmbBoxProgramCode = new javax.swing.JComboBox();
        CmbBoxEnrollment = new javax.swing.JComboBox();
        btSubmit = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        CmbBoxYear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbBoxYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty", "1st Year", "2nd Year", "3rd Year", "Final Year" }));

        CmbBoxProgramCode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbBoxProgramCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty", "CSE", "EE", "ME" }));

        CmbBoxEnrollment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbBoxEnrollment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty", "Active", "Pass out", "Suspend", "Expelled" }));

        btSubmit.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        btBack.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Please Select Year to get Report");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Please Select Program Code to get Report");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Please select Enrollment Status to get the Report");

        btnCancel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSubmit)
                .addGap(18, 18, 18)
                .addComponent(btBack)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmbBoxProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CmbBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CmbBoxEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CmbBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(CmbBoxProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(CmbBoxEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSubmit)
                    .addComponent(btBack)
                    .addComponent(btnCancel))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        if(evt.getSource()==btSubmit)
        {
        //lstrpt=new List();// we can also use JTextArea
		//add(lstrpt);
		//lstrpt.setBounds(10,40,400,300);    
        String year=(String)CmbBoxYear.getSelectedItem().toString();
        String Program_Code=(String)CmbBoxProgramCode.getSelectedItem().toString();
        String Enroll=(String)CmbBoxEnrollment.getSelectedItem().toString();
        if(year.equals("Empty") && Program_Code.equals("Empty")&& Enroll.equals("Empty"))
	{
	javax.swing.JOptionPane.showMessageDialog(null,"Please Select one of three "); // jaswant call the constructor of your student page	
	}
        else if (Program_Code.equals("Empty")&& Enroll.equals("Empty"))
        {
            lstrpt=new List();// we can also use JTextArea
		add(lstrpt);
		lstrpt.setBounds(10,40,400,300);
                try
		{
			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");	
			//System.out.println("Driver loaded successfully");
			Connection con = DriverManager.getConnection("jdbc:odbc:EMS");
			//System.out.println("connection Established Successfully");
			Statement stmt = con.createStatement();
			ResultSet rs = stmt.executeQuery("Select * from Student_Detail WHERE Joining_Year= '" + year + "'");
			String st="";

			while (rs.next())
			{
				st =  rs.getString("Student_ID") + "        "+ rs.getString("first_name")+"        " + rs.getString("last_name")+"       "+rs.getString("dob")+"           "+rs.getString("Program_Code")+"           "+rs.getString("Permanent_Address")+"           "+rs.getString("Enrollment_Status")+"            "+rs.getString("gender")+"";
				lstrpt.add(st);
			}
		}
        catch (Exception e) {
           System.out.print(e);
        }
        } 
        else if (year.equals("Empty")&& Enroll.equals("Empty"))
        {
            lstrpt=new List();// we can also use JTextArea
		add(lstrpt);
		lstrpt.setBounds(10,40,400,300);
                try
		{
			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");	
			//System.out.println("Driver loaded successfully");
			Connection con = DriverManager.getConnection("jdbc:odbc:EMS");
			//System.out.println("connection Established Successfully");
			Statement stmt = con.createStatement();
			ResultSet rs = stmt.executeQuery("Select * from Student_Detail WHERE Program_Code= '" + Program_Code+ "'");
			String st="";

			while (rs.next())
			{
				st =  rs.getString("Student_ID") + "        "+ rs.getString("first_name")+"        " + rs.getString("last_name")+"       "+rs.getString("dob")+"           "+rs.getString("Joining_Year")+"           "+rs.getString("Permanent_Address")+"           "+rs.getString("Enrollment_Status")+"            "+rs.getString("gender")+"";
				lstrpt.add(st);
			}
		}
        catch (Exception e) {
           System.out.print(e);
        }
        }
        else if (year.equals("Empty")&&Program_Code.equals("Empty"))
        {
            lstrpt=new List();// we can also use JTextArea
		add(lstrpt);
		lstrpt.setBounds(10,40,400,300);
                try
		{
			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");	
			//System.out.println("Driver loaded successfully");
			Connection con = DriverManager.getConnection("jdbc:odbc:EMS");
			//System.out.println("connection Established Successfully");
			Statement stmt = con.createStatement();
			ResultSet rs = stmt.executeQuery("Select * from Student_Detail WHERE Enrollment_Status= '" + Enroll+ "'");
			String st="";

			while (rs.next())
			{
				st =  rs.getString("Student_ID") + "        "+ rs.getString("first_name")+"        " + rs.getString("last_name")+"       "+rs.getString("dob")+"           "+rs.getString("Joining_Year")+"           "+rs.getString("Permanent_Address")+"           "+rs.getString("Program_Code")+"            "+rs.getString("gender")+"";
				lstrpt.add(st);
			}
		}
        catch (Exception e) {
           System.out.print(e);
        }
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Please Select only one of three ");
        }}
    }//GEN-LAST:event_btSubmitActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
       StudentReport stdr=new StudentReport();
       stdr.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        EMS ems= new EMS();
        ems.setVisible(true);
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox CmbBoxEnrollment;
    public javax.swing.JComboBox CmbBoxProgramCode;
    public javax.swing.JComboBox CmbBoxYear;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btSubmit;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
        List lstrpt;
}
