
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jaswant
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ComboBoxEnrollment = new javax.swing.JComboBox();
        jPanelStudentDetail = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblIntake = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPassing = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblPermanentAddress = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtIntake = new javax.swing.JTextField();
        txtDOB = new javax.swing.JFormattedTextField();
        jComboBoxjoining = new javax.swing.JComboBox();
        ComboBoxcode = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPermanentAddress = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxEnroll = new javax.swing.JComboBox();
        ComboBoxGender = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        lblRegistration = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        ComboBoxEnrollment.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ComboBoxEnrollment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Studying", "passed", "leaved" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelStudentDetail.setBackground(new java.awt.Color(204, 255, 204));

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 0, 51));
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 0, 51));
        lblLastName.setText("Last Name");

        lblIntake.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblIntake.setForeground(new java.awt.Color(0, 0, 51));
        lblIntake.setText("Intake No.");

        lblDOB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(0, 0, 51));
        lblDOB.setText("Date Of Birth");

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 0, 51));
        lblGender.setText("Gender");

        lblPassing.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPassing.setForeground(new java.awt.Color(0, 0, 51));
        lblPassing.setText("Joining Year");

        lblBranch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBranch.setForeground(new java.awt.Color(0, 0, 51));
        lblBranch.setText("Program Code");

        lblPermanentAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPermanentAddress.setForeground(new java.awt.Color(0, 0, 51));
        lblPermanentAddress.setText("Permanent Address");

        txtFirstName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(0, 0, 51));

        txtLastName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(0, 0, 51));

        txtIntake.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtIntake.setForeground(new java.awt.Color(0, 0, 51));

        txtDOB.setForeground(new java.awt.Color(0, 0, 51));
        txtDOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDOB.setText("mm/dd/yy");

        jComboBoxjoining.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxjoining.setForeground(new java.awt.Color(0, 0, 51));
        jComboBoxjoining.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st Year", "2nd Year", "3rd Year", "Final Year" }));

        ComboBoxcode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ComboBoxcode.setForeground(new java.awt.Color(0, 0, 51));
        ComboBoxcode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "EE", "ME" }));

        txtPermanentAddress.setColumns(20);
        txtPermanentAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPermanentAddress.setForeground(new java.awt.Color(0, 0, 51));
        txtPermanentAddress.setRows(5);
        jScrollPane1.setViewportView(txtPermanentAddress);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Enrollment Status");

        ComboBoxEnroll.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ComboBoxEnroll.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Pass out", "Suspend", "Expelled" }));

        ComboBoxGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male" }));

        javax.swing.GroupLayout jPanelStudentDetailLayout = new javax.swing.GroupLayout(jPanelStudentDetail);
        jPanelStudentDetail.setLayout(jPanelStudentDetailLayout);
        jPanelStudentDetailLayout.setHorizontalGroup(
            jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentDetailLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPermanentAddress)
                    .addComponent(lblBranch)
                    .addComponent(lblPassing)
                    .addComponent(lblGender)
                    .addComponent(lblDOB)
                    .addComponent(lblIntake)
                    .addComponent(lblLastName)
                    .addComponent(lblFirstName)
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxjoining, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxcode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtIntake)
                    .addComponent(txtLastName)
                    .addComponent(txtFirstName)
                    .addComponent(txtDOB)
                    .addGroup(jPanelStudentDetailLayout.createSequentialGroup()
                        .addComponent(ComboBoxEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ComboBoxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelStudentDetailLayout.setVerticalGroup(
            jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentDetailLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntake)
                    .addComponent(txtIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(ComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassing)
                    .addComponent(jComboBoxjoining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranch)
                    .addComponent(ComboBoxcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPermanentAddress))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));

        lblRegistration.setBackground(new java.awt.Color(153, 102, 0));
        lblRegistration.setFont(new java.awt.Font("Mongolian Baiti", 3, 18)); // NOI18N
        lblRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistration.setText("REGISTRATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistration)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnSubmit.setBackground(new java.awt.Color(204, 204, 255));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 102, 0));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 153, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 153, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 204, 255));
        btnCancel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 153, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(204, 204, 255));
        btnReset.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 102, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnSubmit)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelStudentDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelStudentDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      EMS em=new EMS();
       em.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtFirstName.setText("");
        txtLastName.setText("");
        txtIntake.setText("");
        txtDOB.setText("M/d/yy");
        txtPermanentAddress.setText("");
        txtFirstName.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
       if (evt.getSource()==btnSubmit)
	{
		
	String first_name = txtFirstName.getText();
String last_name = txtLastName.getText();
String Student_ID = txtIntake.getText();
String dob=txtDOB.getText();
String Joining_Year=(String)jComboBoxjoining.getSelectedItem().toString();
String Program_Code=(String)ComboBoxcode.getSelectedItem().toString();
String Permanent_Address=txtPermanentAddress.getText();
String Enrollment_Status=(String)ComboBoxEnroll.getSelectedItem().toString();
String gender=(String)ComboBoxGender.getSelectedItem().toString();
if(first_name.equals("")) //|| ppaswd.equals(""))
	{
	javax.swing.JOptionPane.showMessageDialog(null,"First Name empty");
        txtFirstName.requestFocus();
	}
	else if (last_name.equals(""))
	{
		javax.swing.JOptionPane.showMessageDialog(null,"Last Name is empty");
                txtLastName.requestFocus();
	}
else if (Student_ID.equals(""))
	{
		javax.swing.JOptionPane.showMessageDialog(null,"Intake is empty");
                txtIntake.requestFocus();
	}
else if (dob.equals("") || dob.equals("M/d/yy")||dob.equals("M/D/yy") )
	{
		javax.swing.JOptionPane.showMessageDialog(null,"date of birth field is empty");
                txtDOB.requestFocus();
	}
else if (Permanent_Address.equals(""))
	{
		javax.swing.JOptionPane.showMessageDialog(null,"Please Fillup Permanent Address");
                txtPermanentAddress.requestFocus();
	}
else //if(fname.equals("admin") && lname.equals("pass"))
	{
    try{
        int id = Integer.parseInt(Student_ID);
		//step 1 Load the drivers
		//Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");  
	 String url="jdbc:odbc:EMS"; 
         //String source = 
		   //"jdbc:odbc:Driver={Microsoft Access Driver (*.mdb,*.accdb)};DBQ=EMS.accdb";
	 Connection connection = DriverManager.getConnection(url); 
        // Statement state = connect.createStatement();
      Statement stmt =connection.createStatement();
      String sql = "insert into Student_Detail (Student_ID,first_name,last_name,dob,Joining_Year,Program_Code,Permanent_Address,Enrollment_Status,gender) values ('" + id+ "','" + first_name+"','"+last_name+ "','" + dob + "','"+Joining_Year+"','"+Program_Code+"','"+Permanent_Address+"','"+Enrollment_Status+"','"+gender+"')";
       stmt.execute(sql);
        JOptionPane.showMessageDialog(null, "Record added Successfully");
	  stmt.close();
	  connection.close(); 
	}
    catch(Exception e)
	{
            System.out.print(e);
        }}
}
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       if (evt.getSource()==btnUpdate)
       {
           String first_name = txtFirstName.getText();
String last_name = txtLastName.getText();
String Student_ID = txtIntake.getText();
String dob=txtDOB.getText();
String Joining_Year=(String)jComboBoxjoining.getSelectedItem().toString();
String Program_Code=(String)ComboBoxcode.getSelectedItem().toString();
String Permanent_Address=txtPermanentAddress.getText();
String Enrollment_Status=(String)ComboBoxEnroll.getSelectedItem().toString();
        try{
	 String url="jdbc:odbc:EMS";        
	 Connection connect = DriverManager.getConnection(url);
         Statement stmt = connect.createStatement();
         int i=Integer.parseInt(Student_ID);
         String sql = "update Student_Detail set first_name= '"+first_name+"', last_name= '"+last_name+"',dob='"+dob+"', Joining_Year='"+Joining_Year+"', Program_Code='"+Program_Code+"', Permanent_Address='"+Permanent_Address+"', Enrollment_Status='"+Enrollment_Status+"'  WHERE Student_ID= "+i+"";
         stmt.execute(sql);
        JOptionPane.showMessageDialog(null, "Record updated Successfully");
	  stmt.close();
	  connect.close(); 
        }
         catch(Exception e)
	{
            System.out.print(e);
        }}
// TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
 String Student_ID=txtIntake.getText();
		  int i=Integer.parseInt(Student_ID);
          if(evt.getSource()==btnDelete){         
            delete(i);            
          }  
      }

	  void delete(int Student_ID){
        try{
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           Connection connect = DriverManager.getConnection("jdbc:odbc:EMS");
           Statement state = connect.createStatement();
           String sql = "delete from Student_Detail where student_ID="+ Student_ID +"";
           state.execute(sql);
		   JOptionPane.showMessageDialog(null, "Record deleted Successfully");
		   System.out.println("Statement executed successfully");
           state.close();
           connect.close();
		}
        catch (Exception e) {
           System.out.print(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox ComboBoxEnroll;
    private javax.swing.JComboBox ComboBoxEnrollment;
    public javax.swing.JComboBox ComboBoxGender;
    public javax.swing.JComboBox ComboBoxcode;
    javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    public javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox jComboBoxjoining;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelStudentDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIntake;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassing;
    private javax.swing.JLabel lblPermanentAddress;
    private javax.swing.JLabel lblRegistration;
    public javax.swing.JFormattedTextField txtDOB;
    public javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtIntake;
    public javax.swing.JTextField txtLastName;
    public javax.swing.JTextArea txtPermanentAddress;
    // End of variables declaration//GEN-END:variables
}
