
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaswant
 */
public class Subject extends javax.swing.JFrame {

    /**
     * Creates new form Subject
     */
    public Subject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblSubjectManagement = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSubName = new javax.swing.JLabel();
        lblSubID = new javax.swing.JLabel();
        lblSubTecacher = new javax.swing.JLabel();
        lblSem = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtSubName = new javax.swing.JTextField();
        txtSubCode = new javax.swing.JTextField();
        txtSubTeacher = new javax.swing.JTextField();
        CmBoxSem = new javax.swing.JComboBox();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));

        lblSubjectManagement.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblSubjectManagement.setForeground(new java.awt.Color(255, 255, 255));
        lblSubjectManagement.setText("Subject Management");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        lblSubName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSubName.setText("Subject Name");

        lblSubID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSubID.setText("Subject ID");

        lblSubTecacher.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSubTecacher.setText("Subject Teacher");

        lblSem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSem.setText("Semester");

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtSubName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtSubCode.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtSubTeacher.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        CmBoxSem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CmBoxSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8" }));

        btUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btUpdate)
                    .addComponent(btnSubmit)
                    .addComponent(lblSem)
                    .addComponent(lblSubTecacher)
                    .addComponent(lblSubID)
                    .addComponent(lblSubName))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CmBoxSem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSubTeacher)
                            .addComponent(txtSubCode)
                            .addComponent(txtSubName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDelete)
                            .addComponent(btnReset))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancel)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubName)
                    .addComponent(txtSubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubID)
                    .addComponent(txtSubCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTecacher)
                    .addComponent(txtSubTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSem)
                    .addComponent(CmBoxSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdate)
                    .addComponent(btDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblSubjectManagement)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubjectManagement)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
if (evt.getSource()==btnSubmit)
	{
		
	String subject_name = txtSubName.getText();
String subject_ID = txtSubCode.getText();
String subject_teacher = txtSubTeacher.getText();
String semster=(String)CmBoxSem.getSelectedItem().toString();

if(subject_name.equals("")) 
	{
	javax.swing.JOptionPane.showMessageDialog(null,"SubJect Name empty");
        txtSubName.requestFocus();
	}
	else if (subject_ID.equals(""))
	{
		javax.swing.JOptionPane.showMessageDialog(null,"Subject Code is empty");
                txtSubCode.requestFocus();
	}
else if (subject_teacher.equals(""))
	{
		javax.swing.JOptionPane.showMessageDialog(null,"Intake is empty");
                txtSubTeacher.requestFocus();
	}

else //if(fname.equals("admin") && lname.equals("pass"))
	{
	try{
            int id = Integer.parseInt(subject_ID);
		//step 1 Load the drivers
		//Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");  
	 String url="jdbc:odbc:EMS"; 
         //String source = 
		   //"jdbc:odbc:Driver={Microsoft Access Driver (*.mdb,*.accdb)};DBQ=EMS.accdb";
	 Connection connection = DriverManager.getConnection(url); 
        // Statement state = connect.createStatement();
      Statement stmt =connection.createStatement();
      String sql = "insert into Subject_Detail (subject_ID,subject_name,subject_teacher,semster) values ('" + id+ "','" + subject_name+"','"+subject_teacher+ "','" + semster + "')";
      
	  stmt.execute(sql);
JOptionPane.showMessageDialog(null, "Record added Successfully");
	  stmt.close();
	  connection.close(); 
	}
    catch(Exception e)
	{
            System.out.print(e);
        }}

}      // TODO add you   // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
txtSubName.setText("");
        txtSubCode.setText("");
        txtSubTeacher.setText("");
txtSubName.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
                    String subject_ID=txtSubCode.getText();
		  int i=Integer.parseInt(subject_ID);
          if(evt.getSource()==btDelete){         
            delete(i);            
          }  
      }

	  void delete(int subject_ID){
        try{
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		  // System.out.println("Divers loaded successfully");
           Connection connect = DriverManager.getConnection("jdbc:odbc:EMS");
		  // System.out.println("Connection established successfully");
           Statement state = connect.createStatement();
           String sql = "delete from Subject_Detail where subject_ID="+ subject_ID +"";
           state.execute(sql);
		   JOptionPane.showMessageDialog(null, "Record deleted Successfully");
		   System.out.println("Statement executed successfully");
           state.close();
           connect.close();
		}
        catch (Exception e) {
           System.out.print(e);
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        if (evt.getSource()==btUpdate) 
        {
            String subject_name = txtSubName.getText();
String subject_ID = txtSubCode.getText();
String subject_teacher = txtSubTeacher.getText();
String semster =(String)CmBoxSem.getSelectedItem().toString();
            try{
	 String url="jdbc:odbc:EMS";        
	 Connection connect = DriverManager.getConnection(url);
         Statement stmt = connect.createStatement();
         int i=Integer.parseInt(subject_ID);
String sql = "update Subject_Detail set subject_name= '"+subject_name+"', subject_teacher= '"+subject_teacher+"',semster='"+semster+"'  WHERE subject_ID= "+i+"";
         stmt.execute(sql);
        JOptionPane.showMessageDialog(null, "Record added Successfully");
	  stmt.close();
	  connect.close(); 
            }
            catch(Exception e)
	{
            System.out.print(e);
        }}
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
            EMS ems = new EMS();
            ems.setVisible(true);
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox CmBoxSem;
    private javax.swing.JButton btCancel;
    javax.swing.JButton btDelete;
    protected javax.swing.JButton btUpdate;
    protected javax.swing.JButton btnReset;
    public javax.swing.JButton btnSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSem;
    private javax.swing.JLabel lblSubID;
    private javax.swing.JLabel lblSubName;
    private javax.swing.JLabel lblSubTecacher;
    private javax.swing.JLabel lblSubjectManagement;
    private javax.swing.JTextField txtSubCode;
    public javax.swing.JTextField txtSubName;
    public javax.swing.JTextField txtSubTeacher;
    // End of variables declaration//GEN-END:variables
}
