/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaswant
 */
public class EMS extends javax.swing.JFrame {

    /**
     * Creates new form EMS
     */
    public EMS() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        meAdmin = new javax.swing.JMenu();
        meAStudent = new javax.swing.JMenu();
        meItmAddStudent = new javax.swing.JMenuItem();
        Separator3 = new javax.swing.JPopupMenu.Separator();
        meItmDeleteStudent = new javax.swing.JMenuItem();
        Separator4 = new javax.swing.JPopupMenu.Separator();
        meItmsUpdateStudent = new javax.swing.JMenuItem();
        Separator1 = new javax.swing.JPopupMenu.Separator();
        meAEmployee = new javax.swing.JMenu();
        meItemAddEmployee = new javax.swing.JMenuItem();
        Separator5 = new javax.swing.JPopupMenu.Separator();
        meItemsUpdateEmployee = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        Separator2 = new javax.swing.JPopupMenu.Separator();
        meASubject = new javax.swing.JMenu();
        meItmAddSubject = new javax.swing.JMenuItem();
        Separator6 = new javax.swing.JPopupMenu.Separator();
        meItmUpdateSubject = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        meEmploye = new javax.swing.JMenu();
        meEmployeeProfile = new javax.swing.JMenu();
        meItmEmployeeViewProfile = new javax.swing.JMenuItem();
        Separator8 = new javax.swing.JPopupMenu.Separator();
        meItmEmploySearchProfile = new javax.swing.JMenuItem();
        Separator7 = new javax.swing.JPopupMenu.Separator();
        meEmpStudent = new javax.swing.JMenu();
        meItmEmpStudentRemark = new javax.swing.JMenuItem();
        Separator9 = new javax.swing.JPopupMenu.Separator();
        meItmEmpSearchStudent = new javax.swing.JMenuItem();
        meStudent = new javax.swing.JMenu();
        meStudentProfile = new javax.swing.JMenu();
        meitmStudentViewProfile = new javax.swing.JMenuItem();
        Separator11 = new javax.swing.JPopupMenu.Separator();
        meitmStuSearchStudent = new javax.swing.JMenuItem();
        Separator10 = new javax.swing.JPopupMenu.Separator();
        meExam = new javax.swing.JMenu();
        meitmResult = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        meAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        meAdmin.setText("Admin");
        meAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meAdminActionPerformed(evt);
            }
        });

        meAStudent.setText("Student");

        meItmAddStudent.setText("Add Student");
        meItmAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItmAddStudentActionPerformed(evt);
            }
        });
        meAStudent.add(meItmAddStudent);
        meAStudent.add(Separator3);

        meItmDeleteStudent.setText("Delete Student");
        meItmDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItmDeleteStudentActionPerformed(evt);
            }
        });
        meAStudent.add(meItmDeleteStudent);
        meAStudent.add(Separator4);

        meItmsUpdateStudent.setText("Update Student");
        meItmsUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItmsUpdateStudentActionPerformed(evt);
            }
        });
        meAStudent.add(meItmsUpdateStudent);

        meAdmin.add(meAStudent);
        meAdmin.add(Separator1);

        meAEmployee.setText("Employee");
        meAEmployee.setToolTipText("");

        meItemAddEmployee.setText("Add Employee");
        meItemAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItemAddEmployeeActionPerformed(evt);
            }
        });
        meAEmployee.add(meItemAddEmployee);
        meAEmployee.add(Separator5);

        meItemsUpdateEmployee.setText("Update Employee");
        meItemsUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItemsUpdateEmployeeActionPerformed(evt);
            }
        });
        meAEmployee.add(meItemsUpdateEmployee);
        meAEmployee.add(jSeparator2);

        jMenuItem2.setText("Delete Employee");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        meAEmployee.add(jMenuItem2);

        meAdmin.add(meAEmployee);
        meAdmin.add(Separator2);

        meASubject.setText("Subject");

        meItmAddSubject.setText("Add Subject");
        meItmAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItmAddSubjectActionPerformed(evt);
            }
        });
        meASubject.add(meItmAddSubject);
        meASubject.add(Separator6);

        meItmUpdateSubject.setText("Update Subject");
        meItmUpdateSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItmUpdateSubjectActionPerformed(evt);
            }
        });
        meASubject.add(meItmUpdateSubject);
        meASubject.add(jSeparator1);

        jMenuItem1.setText("Delete Subject");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        meASubject.add(jMenuItem1);

        meAdmin.add(meASubject);

        jMenuBar1.add(meAdmin);

        meEmploye.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        meEmploye.setText("Employee");

        meEmployeeProfile.setText("Profile");

        meItmEmployeeViewProfile.setText("View All Employee");
        meItmEmployeeViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItmEmployeeViewProfileActionPerformed(evt);
            }
        });
        meEmployeeProfile.add(meItmEmployeeViewProfile);
        meEmployeeProfile.add(Separator8);

        meItmEmploySearchProfile.setText("Search Employee Profile");
        meEmployeeProfile.add(meItmEmploySearchProfile);

        meEmploye.add(meEmployeeProfile);
        meEmploye.add(Separator7);

        meEmpStudent.setText("Student");

        meItmEmpStudentRemark.setText("Student's Remarks");
        meEmpStudent.add(meItmEmpStudentRemark);
        meEmpStudent.add(Separator9);

        meItmEmpSearchStudent.setText("Search Student");
        meItmEmpSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItmEmpSearchStudentActionPerformed(evt);
            }
        });
        meEmpStudent.add(meItmEmpSearchStudent);

        meEmploye.add(meEmpStudent);

        jMenuBar1.add(meEmploye);

        meStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        meStudent.setText("Student");

        meStudentProfile.setText("Profile");

        meitmStudentViewProfile.setText("ViewAll Student");
        meitmStudentViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meitmStudentViewProfileActionPerformed(evt);
            }
        });
        meStudentProfile.add(meitmStudentViewProfile);
        meStudentProfile.add(Separator11);

        meitmStuSearchStudent.setText("Search Student");
        meitmStuSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meitmStuSearchStudentActionPerformed(evt);
            }
        });
        meStudentProfile.add(meitmStuSearchStudent);

        meStudent.add(meStudentProfile);
        meStudent.add(Separator10);

        meExam.setText("Examination");

        meitmResult.setText("Results");
        meExam.add(meitmResult);

        meStudent.add(meExam);

        jMenuBar1.add(meStudent);

        jMenu1.setText("Subject");
        jMenu1.add(jSeparator3);

        jMenuItem3.setText("View Report");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Search Subject");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("LOGOUT");

        jMenuItem4.setText("Logout");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meitmStuSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meitmStuSearchStudentActionPerformed
        StudentDetail stdl= new StudentDetail();
        stdl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_meitmStuSearchStudentActionPerformed

    private void meItmAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItmAddStudentActionPerformed
        Student stu = new Student();
        stu.setVisible(true);  
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meItmAddStudentActionPerformed

    private void meItmDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItmDeleteStudentActionPerformed
       Student stu = new Student();
        stu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meItmDeleteStudentActionPerformed

    private void meItmsUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItmsUpdateStudentActionPerformed
            Student stu = new Student();
        stu.setVisible(true);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meItmsUpdateStudentActionPerformed

    private void meItemAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItemAddEmployeeActionPerformed
            Employee emp = new Employee();
        emp.setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meItemAddEmployeeActionPerformed

    private void meItemsUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItemsUpdateEmployeeActionPerformed
        Employee emp = new Employee();
        emp.setVisible(true);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meItemsUpdateEmployeeActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            Employee emp = new Employee();
        emp.setVisible(true);  
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void meItmAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItmAddSubjectActionPerformed
                Subject sub = new Subject();
                 sub.setVisible(true);
                 this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meItmAddSubjectActionPerformed

    private void meItmUpdateSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItmUpdateSubjectActionPerformed
                    Subject sub = new Subject();
                 sub.setVisible(true);    
                 this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meItmUpdateSubjectActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                Subject sub = new Subject();
                 sub.setVisible(true); 
                 this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void meitmStudentViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meitmStudentViewProfileActionPerformed
       StudentReport stdr = new StudentReport();
       stdr.setVisible(true);
       this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meitmStudentViewProfileActionPerformed

    private void meItmEmployeeViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItmEmployeeViewProfileActionPerformed
      EmpReport empr = new EmpReport();
       empr.setVisible(true);
       this.dispose();
       // TODO add your handling code here:
    }//GEN-LAST:event_meItmEmployeeViewProfileActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            SubReport srt = new SubReport();
            srt.setVisible(true);
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void meAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meAdminActionPerformed

    private void meItmEmpSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItmEmpSearchStudentActionPerformed
            StudentDetail std = new StudentDetail();
            std.setVisible(true);
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_meItmEmpSearchStudentActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
            Login ln= new Login();
            ln.setVisible(true);
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
            SubjectSearch subs= new SubjectSearch();
            subs.setVisible(true);
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed
        public void disable(boolean x)
    {
     if (x==true)
    {
        meAdmin.setEnabled(false);
        //jMenu6.setEnabled(false);
    }
    else if (x==false)
    {
        meAdmin.setEnabled(false);
         meEmploye.setEnabled(false);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator Separator1;
    private javax.swing.JPopupMenu.Separator Separator10;
    private javax.swing.JPopupMenu.Separator Separator11;
    private javax.swing.JPopupMenu.Separator Separator2;
    private javax.swing.JPopupMenu.Separator Separator3;
    private javax.swing.JPopupMenu.Separator Separator4;
    private javax.swing.JPopupMenu.Separator Separator5;
    private javax.swing.JPopupMenu.Separator Separator6;
    private javax.swing.JPopupMenu.Separator Separator7;
    private javax.swing.JPopupMenu.Separator Separator8;
    private javax.swing.JPopupMenu.Separator Separator9;
    protected javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public javax.swing.JMenu meAEmployee;
    public javax.swing.JMenu meAStudent;
    public javax.swing.JMenu meASubject;
    public javax.swing.JMenu meAdmin;
    public javax.swing.JMenu meEmpStudent;
    public javax.swing.JMenu meEmploye;
    public javax.swing.JMenu meEmployeeProfile;
    public javax.swing.JMenu meExam;
    private javax.swing.JMenuItem meItemAddEmployee;
    private javax.swing.JMenuItem meItemsUpdateEmployee;
    private javax.swing.JMenuItem meItmAddStudent;
    private javax.swing.JMenuItem meItmAddSubject;
    private javax.swing.JMenuItem meItmDeleteStudent;
    private javax.swing.JMenuItem meItmEmpSearchStudent;
    private javax.swing.JMenuItem meItmEmpStudentRemark;
    javax.swing.JMenuItem meItmEmploySearchProfile;
    javax.swing.JMenuItem meItmEmployeeViewProfile;
    private javax.swing.JMenuItem meItmUpdateSubject;
    private javax.swing.JMenuItem meItmsUpdateStudent;
    public javax.swing.JMenu meStudent;
    private javax.swing.JMenu meStudentProfile;
    javax.swing.JMenuItem meitmResult;
    javax.swing.JMenuItem meitmStuSearchStudent;
    javax.swing.JMenuItem meitmStudentViewProfile;
    // End of variables declaration//GEN-END:variables
}
